apiVersion: v1
kind: Service
metadata:
  name: cidep-service
spec:
  type: LoadBalancer
  selector:
    app: cidep
    version: blue  # or green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
